export default [

  { category: "All", path: 'images/portfolio/2.png' },
  { category: "All", path: 'images/portfolio/3.png' },
  { category: "All", path: 'images/portfolio/2.png' },
  { category: "All", path: 'images/portfolio/3.png' },
  { category: "All", path: 'images/portfolio/2.png' },
  { category: "All", path: 'images/portfolio/3.png' },
  { category: "All", path: 'images/portfolio/1.png' },
  { category: "All", path: 'images/portfolio/4.png' },
  { category: "All", path: 'images/portfolio/1.png' },
  { category: "All", path: 'images/portfolio/4.png' },
  { category: "All", path: 'images/portfolio/1.png' },
  { category: "All", path: 'images/portfolio/4.png' },

  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },
  { category: "Web", path: 'images/portfolio/2.png' },

  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },
  { category: "Photography", path: 'images/portfolio/3.png' },

  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' },
  { category: "Graphic design", path: 'images/portfolio/4.png' }

];